[lint]
enabled_rules = [
    "strictness/require-return-type",
    "strictness/require-parameter-type",
    "best-practices/no-unused-parameter",
    "correctness/no-undefined-method",
    "clarity/no-undef",
]

[lint.levels]
"correctness/no-undefined-method" = "error"
"strictness/require-return-type" = "warning"

[format]
line_width = 120
indent_style = "space"
indent_size = 4

[analyze]
paths = ["src/"]
